# .github/workflows/go.yml
name: Go

on:
  push:
    branches: [ "**" ]
    paths:
      - "**/*.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/go.yml"
  pull_request:
    branches: [ "**" ]
    paths:
      - "**/*.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/go.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Benchmark
        working-directory: ./bench
        run: go test -bench=. -cpuprofile=cpu.prof -memprofile=mem.prof -benchmem

      - name: Upload benchmark profiles
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-profiles
          path: |
            bench/cpu.prof
            bench/mem.prof
